### ISSUE TITLE
Chrome version broken with sync changes

### ISSUE THREAD

**Issue by kav2k** [Rob--W/stackexchange-notifications#16]
Looks like #11 broke the Chrome version.

[This line](https://github.com/Rob--W/stackexchange-notifications/commit/9bf0d62a9140a03847226dd5118c539b333e04fa#diff-e5371e7005aa23b189491152872f5565R25) from migration code fails because `storage` is undefined, grinding the extension to a halt.

Mea culpa for not finding time to get an API key to test #11, I suppose.

**Comment by kav2k** [comment]
Funny how I did not notice it for a full month, nor any of your other users.

**Comment by Rob--W** [comment]
Patches are welcome ;)

If you don't have time to submit a PR, I'll commit a patch tomorrow.
