### ISSUE TITLE
Extension gets confused by reputation change messages

### ISSUE THREAD

**Issue by kav2k** [Rob--W/stackexchange-notifications#18]
When subscribing to topbar messages, extension will receive rep change notifications, e.g.

    {"action":"897255-topbar","data":"{\"Achievements\":{\"UnreadRepCount\":0,\"UnreadNonRepCount\":0}}"}

Code in `using-websocket.js:162` just assumes that the message has `data.Inbox` and fails with a 

> Uncaught TypeError: Cannot read property 'UnreadInboxCount' of undefined

**Comment by Rob--W** [comment]
Fixed, I will wait with publishing an update until the other issue gets resolved.
