### ISSUE TITLE
Display an icon with number of unread messages?

### ISSUE THREAD

**Issue by orschiro** [Rob--W/stackexchange-notifications#20]
Dear @Rob--W,

What a fantastic extension. 

Thank you very much!

Would it be possible to add a button that one can add to the list of buttons and that would display a counter of the number of unread messages in the inbox?

![image](https://cloud.githubusercontent.com/assets/170947/14402814/1ea7c31e-fe40-11e5-8146-98a8cfcce044.png)

What are your thoughts?

Thankfully,

~Robert

**Comment by Rob--W** [comment]
Done.

**Comment by orschiro** [comment]
Dear @Rob--W,

I just received the update and it is working beautifully. 

Thank you so much!

~Robert
