### ISSUE TITLE
Show number of unread items in icon?

### ISSUE THREAD

**Issue by orschiro** [Rob--W/stackexchange-notifications#24]
Dear @Rob--W, 

What a fantastic extension. 

Thank you so much!

May I suggest one new feature?

What do you think about displaying the number of unread items as follows:

![image](https://cloud.githubusercontent.com/assets/170947/17248342/33dfbfdc-559a-11e6-8e89-792d6bec0e05.png)

Thankfully,

~Robert

:-)

**Comment by orschiro** [comment]
Apologies for my request!

It already exists and I just didn't notice. :-)

![image](https://cloud.githubusercontent.com/assets/170947/17250141/50383f70-55a3-11e6-9f62-142943bfaa77.png)

**Comment by Rob--W** [comment]
This was indeed implemented after your request in #20. The counter only appears if you have a notification. If the notification does not show up, check whether the socket connection is still open, and if not activate it (also try to Stop and then Start the socket if you're not sure whether it's working). You can do that from the options page.

**Comment by orschiro** [comment]
That's excellent, thanks Rob! :-)
