### ISSUE TITLE
Notification counter not updated

### ISSUE THREAD

**Issue by orschiro** [Rob--W/stackexchange-notifications#25]
Dear @Rob--W, 

For some reasons, the icon keeps showing me two new notifications that are already marked as read on stackexchange. 

Any ideas?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17363050/9d921100-5978-11e6-84af-d09d3cfe5c4b.png)

**Comment by Rob--W** [comment]
I just tried, and it works.

Did you authenticate with the addon ("Grant Token" button)? The realtime notifications use WebSockets. But if you get a notification update while the WebSocket is down (e.g. when you get a notification, disconnect your computer from the internet and use your mobile phone to read the notification), then the extension is not notified of the change.

To counter that, you have to click on the "Grant Token" button. Then an oAuth dialog opens where you can log in with your Stack Exchange account. With this access, the extension can request the actual unread notification count when it discovers that the WebSocket is down.

**Comment by orschiro** [comment]
Hi Rob, 

I checked the token settings and they all seem to be fine. 

![image](https://cloud.githubusercontent.com/assets/170947/17528143/72846a30-5e6e-11e6-91de-95d6373ed963.png)

Could it be a problem related to a very slow internet connection?

I am currently using a very slow connection and maybe therefore the notifications are not properly being checked?

Strangely, the notifications are now synchronised again meaning that the icon does not display any new notifications anymore which indeed is the case because I checked all of them.

Well, for now I would say that my issue is solved. 

I appreciate your advice though!

~Robert

**Comment by Rob--W** [comment]
> Could it be a problem related to a very slow internet connection?

Having a slow network connection is not a problem, having an unstable on is (because then packets are dropped in an unrecoverable way). But I do expect the fallback logic to kick in and request the latest status (and since the issue is solved for now, it seems to work well).

**Comment by orschiro** [comment]
> having an unstable on is

That's a good characterisation of my connection! It frequently disconnects. 

However, for now it's working again. 

Thank you for your help!

~Robert
