### ISSUE TITLE
Update Firefox add-on for electrolysis

### ISSUE THREAD

**Issue by protist** [Rob--W/stackexchange-notifications#26]
According to "Add-on Compatibility Reporter", the Firefox add-on is not compatible with electrolysis. Would it be possible to upgrade it so we can use multi-process Firefox? Cheers.

![screenshot_at_20161212_11 09 46](https://cloud.githubusercontent.com/assets/646668/21084693/8daeb762-c05b-11e6-8e98-d236b441b6c1.png)

**Comment by Rob--W** [comment]
Done. Thanks for reminding me to do so.
