### ISSUE TITLE
Only show unread counter?

### ISSUE THREAD

**Issue by orschiro** [Rob--W/stackexchange-notifications#27]
Dear @Rob--W,

Would it be possible to add an option to hide the notification cards and only show an unread counter?

Yours,

-Robert

:-)

**Comment by Rob--W** [comment]
This is technically not impossible; but why don't you want to get desktop notifications? Do you never want to see desktop notifications at all, or get the ability to temporarily suppress desktop notifications (i.e. #5)?

**Comment by orschiro** [comment]
Exactly!

I find these desktop notifications very disturbing and prefer to only look at the icon to get an update. :-)

**Comment by Rob--W** [comment]
Implemented and published as version 1.6.12. Please close the issue when the update gets through and you've verified that it works as expected.

**Comment by orschiro** [comment]
Fantastic, thank you so much! :-)

I am just assuming it works if I tick it off. 

![image](https://cloud.githubusercontent.com/assets/170947/22150840/8f18b15a-df1b-11e6-849f-6d9e2ba623be.png)
