### ISSUE TITLE
Update for Firefox 57

### ISSUE THREAD

**Issue by protist** [Rob--W/stackexchange-notifications#29]
Firefox 57 is finally here, and over half my add-ons are broken. 🙁

Is there any possibility to port this to the latest version of Firefox?

**Comment by Rob--W** [comment]
Okay.

**Comment by Rob--W** [comment]
I have ported the extension. There are no obvious errors, but I haven't tested it with full notifications.

Can you try out the extension and report whether it works? If it does then I will publish it.

You can either use `make firefox` to build the Firefox add-on from source, or copy all files in `Chrome/` to `Firefox/` (except for manifest.json).

**Comment by protist** [comment]
Thank you for that quick response!

I tried installing the the first way, but I'm having trouble installing it because the xpi is unsigned. I was wondering if you could possibly sign it so that I can install/test it on the current Firefox version.

See [here](https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ), under `How do I get my add-ons signed if they are not hosted on addons.mozilla.org (AMO)?`

**Comment by Rob--W** [comment]
You can load temporarily load an extension without signing it by going to `about:debugging` and selecting the `manifest.json` file in the directory of an unpacked extension, or the `.xpi` file if you are trying to load a packaged extension.

**Comment by Rob--W** [comment]
Published as version 2.0 to AMO.

**Comment by protist** [comment]
Thanks Rob, sorry, it was night time here!

It installs perfectly, and the notifications work too. Thank you for the quick response again!
