### ISSUE TITLE
Feature request: change position of notification

### ISSUE THREAD

**Issue by protist** [Rob--W/stackexchange-notifications#3]
It'd be great if users could change the position of the notification window. Currently it's in a corner of the screen that I ignore. :see_no_evil:

(Sorry, I just realised github did emoji.)

**Comment by kskollepara** [comment]
This solution doesn't seem to work on Firefox 53

**Comment by Rob--W** [comment]
@kskollepara That is because Firefox attempts to integrate in the OS's native notification system.

Install my No Native Notifications add-on to regain control of the position of the notification:
https://addons.mozilla.org/en-us/firefox/addon/no-native-notifications/

**Comment by odil-io** [comment]
Confirmed, this solution doe not work on FireFox 61 Quantum.
